# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0d20d4d15f902e57708e8eb3f7cba2e089be987acce25cce227cdbb59637991834c2cc22241b7a4df44f3f8fe1bbd7977f50c85c2b7b0a7a4988dbfa0994921

test:
  secret_key_base: 7b542b163d16080c691ead3841be256c84b0e13f75937fb0b4e9f7dbc20068c4ece740509286dcf7038d050469eddf56376dad6961ad1438936bed01fdbddcd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
